import {NextResponse} from "next/server";
import {getSession} from "@/lib/session";
import {loadState,saveState,loadStateVersioned,saveStateIfUnchanged} from "@/lib/db";
import {deleteAuthUser} from "@/lib/supabase-auth";

async function admin(){const sess=await getSession();return sess?.role==="agency_admin"?sess:null}
export async function GET(_req,{params}){const sess=await admin();if(!sess)return NextResponse.json({error:"Accès refusé"},{status:403});const {id}=await params;const s=await loadState();const item=s.instituts.find(x=>x.id===id);return item?NextResponse.json({institut:item}):NextResponse.json({error:"Compte introuvable"},{status:404})}
export async function PATCH(req,{params}){try{const sess=await admin();if(!sess)return NextResponse.json({error:"Accès refusé"},{status:403});const {id}=await params,b=await req.json();
 // V21.44.3 — Les attributions ne transitent plus par le PUT /api/state (payload CRM complet).
 // On relit l'état côté serveur, on ne modifie que les intégrations du compte, puis CAS.
 if(b?.action==='save_assignments'){
  for(let attempt=1;attempt<=5;attempt++){
   const snap=await loadStateVersioned(),s=snap.state,item=s.instituts.find(x=>x.id===id);if(!item)return NextResponse.json({error:"Compte introuvable"},{status:404});
   const locationId=String(b.locationId||''),locationName=String(b.locationName||''),adAccountId=String(b.adAccountId||''),adAccountNumericId=String(b.adAccountNumericId||'').replace(/^act_/,''),adAccountName=String(b.adAccountName||''),currency=String(b.currency||'EUR');
   const currentGhl=(s.integrations||[]).find(x=>x.institutId===id&&x.provider==='ghl');const currentMeta=(s.integrations||[]).find(x=>x.institutId===id&&x.provider==='meta');const now=new Date().toISOString();let integrations=[...(s.integrations||[])];
   const ghlId=currentGhl?.id||`ghl-${id}`;const nextGhl={...(currentGhl||{}),id:ghlId,institutId:id,provider:'ghl',locationId,locationName:locationName||currentGhl?.locationName||'',connected:Boolean(locationId),forms:currentGhl?.forms||[],updatedAt:now};integrations=currentGhl?integrations.map(x=>x.id===currentGhl.id?nextGhl:x):[...integrations,nextGhl];
   if(adAccountId){const metaId=currentMeta?.id||`meta-${id}`;const nextMeta={...(currentMeta||{}),id:metaId,institutId:id,provider:'meta',connected:true,adAccountId,adAccountNumericId:adAccountNumericId||adAccountId.replace(/^act_/,''),adAccountName:adAccountName||adAccountId,currency,campaignMappings:currentMeta?.campaignMappings||[],updatedAt:now};integrations=currentMeta?integrations.map(x=>x.id===currentMeta.id?nextMeta:x):[...integrations,nextMeta]}else if(currentMeta){integrations=integrations.map(x=>x.id===currentMeta.id?{...x,connected:false,adAccountId:'',adAccountNumericId:'',adAccountName:'',updatedAt:now}:x)}
   if(await saveStateIfUnchanged({...s,integrations},snap.updatedAt,snap.previous))return NextResponse.json({ok:true});await new Promise(r=>setTimeout(r,30*attempt));
  }
  return NextResponse.json({error:"Conflit de synchronisation, réessayez dans quelques secondes"},{status:409});
 }
 const s=await loadState();const item=s.instituts.find(x=>x.id===id);if(!item)return NextResponse.json({error:"Compte introuvable"},{status:404});const hasArchived=Object.prototype.hasOwnProperty.call(b,'archived'),archived=hasArchived?Boolean(b.archived):Boolean(item.archived),name=typeof b.name==='string'?b.name.trim():'';if(Object.prototype.hasOwnProperty.call(b,'name')&&!name)return NextResponse.json({error:'Le nom du compte ne peut pas être vide'},{status:400});const next={...s,instituts:s.instituts.map(x=>x.id===id?{...x,...(name?{name,companyName:name}:{}),...(hasArchived?{archived,active:!archived}:{})}:x),users:hasArchived?s.users.map(u=>u.role==='client'&&u.institutId===id?{...u,active:!archived}:u):s.users};await saveState(next);return NextResponse.json({ok:true,archived,name:name||item.companyName||item.name})}catch(e){return NextResponse.json({error:e.message||"Impossible de modifier le compte"},{status:500})}}
export async function DELETE(req,{params}){try{const sess=await admin();if(!sess)return NextResponse.json({error:"Accès refusé"},{status:403});const {id}=await params,b=await req.json().catch(()=>({})),s=await loadState();const item=s.instituts.find(x=>x.id===id);if(!item)return NextResponse.json({error:"Compte introuvable"},{status:404});const expected=String(item.companyName||item.name||'').trim();if(String(b.confirmName||'').trim()!==expected)return NextResponse.json({error:"Le nom de confirmation ne correspond pas"},{status:400});const clientUsers=s.users.filter(u=>u.role==='client'&&u.institutId===id);for(const u of clientUsers){if(u.authUserId)await deleteAuthUser(u.authUserId)}const next={...s,instituts:s.instituts.filter(x=>x.id!==id),users:s.users.filter(u=>!(u.role==='client'&&u.institutId===id)).map(u=>({...u,accessIds:(u.accessIds||[]).filter(x=>x!==id),institutId:u.role==='setter'&&u.institutId===id?((u.accessIds||[]).filter(x=>x!==id)[0]||null):u.institutId})),campaigns:(s.campaigns||[]).filter(x=>x.institutId!==id),leads:(s.leads||[]).filter(x=>x.institutId!==id),expenses:(s.expenses||[]).filter(x=>x.institutId!==id),reviews:(s.reviews||[]).filter(x=>x.institutId!==id),integrations:(s.integrations||[]).filter(x=>x.institutId!==id),notifications:(s.notifications||[]).filter(x=>x.institutId!==id)};await saveState(next);return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:e.message||"Impossible de supprimer le compte"},{status:500})}}
export async function POST(){return NextResponse.json({error:"Méthode non supportée"},{status:405})}
export async function PUT(){return NextResponse.json({error:"Méthode non supportée"},{status:405})}
