import {NextResponse} from "next/server";
import {getSession} from "@/lib/session";
import {loadState,saveState} from "@/lib/db";
import {deleteAuthUser} from "@/lib/supabase-auth";

async function admin(){const sess=await getSession();return sess?.role==="agency_admin"?sess:null}
export async function GET(_req,{params}){const sess=await admin();if(!sess)return NextResponse.json({error:"Accès refusé"},{status:403});const {id}=await params;const s=await loadState();const item=s.instituts.find(x=>x.id===id);return item?NextResponse.json({institut:item}):NextResponse.json({error:"Compte introuvable"},{status:404})}
export async function PATCH(req,{params}){try{const sess=await admin();if(!sess)return NextResponse.json({error:"Accès refusé"},{status:403});const {id}=await params,b=await req.json(),s=await loadState();const item=s.instituts.find(x=>x.id===id);if(!item)return NextResponse.json({error:"Compte introuvable"},{status:404});const archived=Boolean(b.archived);const next={...s,instituts:s.instituts.map(x=>x.id===id?{...x,archived,active:!archived}:x),users:s.users.map(u=>u.role==='client'&&u.institutId===id?{...u,active:!archived}:u)};await saveState(next);return NextResponse.json({ok:true,archived})}catch(e){return NextResponse.json({error:e.message||"Impossible de modifier le compte"},{status:500})}}
export async function DELETE(req,{params}){try{const sess=await admin();if(!sess)return NextResponse.json({error:"Accès refusé"},{status:403});const {id}=await params,b=await req.json().catch(()=>({})),s=await loadState();const item=s.instituts.find(x=>x.id===id);if(!item)return NextResponse.json({error:"Compte introuvable"},{status:404});const expected=String(item.companyName||item.name||'').trim();if(String(b.confirmName||'').trim()!==expected)return NextResponse.json({error:"Le nom de confirmation ne correspond pas"},{status:400});const clientUsers=s.users.filter(u=>u.role==='client'&&u.institutId===id);for(const u of clientUsers){if(u.authUserId)await deleteAuthUser(u.authUserId)}const next={...s,instituts:s.instituts.filter(x=>x.id!==id),users:s.users.filter(u=>!(u.role==='client'&&u.institutId===id)).map(u=>({...u,accessIds:(u.accessIds||[]).filter(x=>x!==id),institutId:u.role==='setter'&&u.institutId===id?((u.accessIds||[]).filter(x=>x!==id)[0]||null):u.institutId})),campaigns:(s.campaigns||[]).filter(x=>x.institutId!==id),leads:(s.leads||[]).filter(x=>x.institutId!==id),expenses:(s.expenses||[]).filter(x=>x.institutId!==id),reviews:(s.reviews||[]).filter(x=>x.institutId!==id),integrations:(s.integrations||[]).filter(x=>x.institutId!==id),notifications:(s.notifications||[]).filter(x=>x.institutId!==id)};await saveState(next);return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:e.message||"Impossible de supprimer le compte"},{status:500})}}
export async function POST(){return NextResponse.json({error:"Méthode non supportée"},{status:405})}
export async function PUT(){return NextResponse.json({error:"Méthode non supportée"},{status:405})}
