import {NextResponse} from "next/server";import {loadState,saveState} from "@/lib/db";import {getSession,visibleState,allowedIds} from "@/lib/session";import {migrate} from "@/lib/state";export const dynamic="force-dynamic";

const scrubSecrets=state=>{const installs=Array.isArray(state?.ghlOAuth?.installations)?state.ghlOAuth.installations:[];const agency=state?.ghlOAuth?.agencyToken||null;const safeAgency=agency?((({accessToken,refreshToken,...rest})=>({...rest,tokenConfigured:Boolean(accessToken),refreshConfigured:Boolean(refreshToken)}))(agency)):null;return {...state,ghlOAuth:{...(state.ghlOAuth||{}),agencyToken:safeAgency,installations:installs.map(({accessToken,refreshToken,...x})=>({...x,tokenConfigured:Boolean(accessToken),refreshConfigured:Boolean(refreshToken)}))},integrations:(state.integrations||[]).map(x=>{if(x.provider!=="ghl")return x;const {apiToken,...safe}=x;return {...safe,apiTokenConfigured:Boolean(apiToken||x.apiTokenConfigured)}})}};
const preserveSecrets=(next,current)=>(next||[]).map(x=>{if(x.provider!=="ghl")return x;const old=(current||[]).find(y=>(y.id&&y.id===x.id)||(y.provider==="ghl"&&y.institutId===x.institutId));return {...x,apiToken:old?.apiToken||x.apiToken||"",apiTokenConfigured:Boolean(old?.apiToken||x.apiToken||x.apiTokenConfigured)}});
const mergeList=(current,incoming)=>{const out=[...(Array.isArray(current)?current:[])],index=new Map(out.map((x,i)=>[x?.id??JSON.stringify(x),i]));for(const item of Array.isArray(incoming)?incoming:[]){const key=item?.id??JSON.stringify(item),i=index.get(key);if(i===undefined){index.set(key,out.length);out.push(item)}else out[i]=item}return out};
const mergeCommercial=(current,incoming)=>{const out={...(current||{})};for(const [cat,track] of Object.entries(incoming||{}))out[cat]={...(out[cat]||{}),...(track||{})};return out};
const mergeLead=(current,patch)=>{const out={...(current||{}),...(patch||{})};if(Object.prototype.hasOwnProperty.call(patch||{},'commercialByCategory'))out.commercialByCategory=mergeCommercial(current?.commercialByCategory,patch.commercialByCategory);for(const key of ['activity','formSubmissions'])if(Object.prototype.hasOwnProperty.call(patch||{},key))out[key]=mergeList(current?.[key],patch[key]);return out};
function applyLeadMutation(current,mutation,allowed=null){const can=id=>!allowed||allowed.has(id);const deleted=new Set((mutation?.deletedLeadIds||[]).filter(can));const changes=(mutation?.leadChanges||[]).filter(x=>x?.id&&can(x.id));let leads=(current.leads||[]).filter(x=>!deleted.has(x.id));const pos=new Map(leads.map((x,i)=>[x.id,i]));for(const change of changes){const i=pos.get(change.id);if(i===undefined){const lead=mergeLead(null,{id:change.id,...(change.patch||{})});pos.set(change.id,leads.length);leads.push(lead)}else leads[i]=mergeLead(leads[i],change.patch||{})}return leads}

export async function GET(req){try{const sess=await getSession();const bootstrap=new URL(req.url).searchParams.get("bootstrap")==="1";if(!sess)return bootstrap?NextResponse.json({user:null,state:null}):NextResponse.json({error:"Non autorisé"},{status:401});const current=await loadState();if(bootstrap){const u=current.users.find(x=>x.id===sess.userId&&x.active!==false);if(!u)return NextResponse.json({user:null,state:null},{status:401});const accessIds=Array.isArray(u.accessIds)&&u.accessIds.length?u.accessIds:(u.institutId?[u.institutId]:[]);return NextResponse.json({user:{id:u.id,name:u.name,email:u.email,role:u.role,institutId:u.institutId||accessIds[0]||null,accessIds},state:scrubSecrets(visibleState(current,sess))})}return NextResponse.json({state:scrubSecrets(visibleState(current,sess))})}catch(e){return NextResponse.json({error:e.message},{status:500})}}
export async function PUT(req){try{const sess=await getSession();if(!sess)return NextResponse.json({error:"Non autorisé"},{status:401});const body=await req.json(),incoming=migrate(body.state),mutation=body.mutation||null,current=await loadState();if(sess.role==="agency_admin"){incoming.users=current.users;incoming.integrations=preserveSecrets(incoming.integrations,current.integrations);incoming.ghlOAuth=current.ghlOAuth||incoming.ghlOAuth;const next=mutation?{...incoming,leads:applyLeadMutation(current,mutation)}:incoming;await saveState(next);return NextResponse.json({ok:true})}
 const ids=allowedIds(sess)||[],idSet=new Set(ids);const ownInst=incoming.instituts.filter(x=>ids.includes(x.id));const safeInstituts=current.instituts.map(old=>{const inc=ownInst.find(x=>x.id===old.id);if(!inc)return old;if(sess.role==="setter")return old;return {...old,name:inc.name||old.name,companyName:inc.companyName||inc.name||old.companyName,ville:inc.ville??old.ville,email:inc.email??old.email,telephone:inc.telephone??old.telephone,address:inc.address??old.address,website:inc.website??old.website,categories:inc.categories||old.categories,pipeline:inc.pipeline||old.pipeline};});
 const mergeScope=(key)=>[...current[key].filter(x=>!ids.includes(x.institutId)),...incoming[key].filter(x=>ids.includes(x.institutId))];const allowedLeadIds=new Set([...(current.leads||[]),...(incoming.leads||[])].filter(x=>idSet.has(x.institutId)).map(x=>x.id));const mergedLeads=mutation?applyLeadMutation(current,mutation,allowedLeadIds):mergeScope("leads");const mergedIntegrations=sess.role==="setter"?current.integrations:preserveSecrets(mergeScope("integrations"),current.integrations);
 await saveState({...current,instituts:safeInstituts,leads:mergedLeads,reviews:mergeScope("reviews"),integrations:mergedIntegrations});return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:e.message},{status:500})}}
