import {NextResponse} from "next/server";import {loadState,saveState} from "@/lib/db";import {uid,today,nowIso,normalizeLead} from "@/lib/state";
const pick=(b,...keys)=>{for(const k of keys){const v=k.includes('.')?k.split('.').reduce((o,p)=>o?.[p],b):b?.[k];if(v!==undefined&&v!==null&&v!=="")return v}return ""};
const reserved=new Set(['location_id','locationId','form_id','formId','form_submission_id','contact_id','contactId','id','email','phone','telephone','first_name','firstName','prenom','last_name','lastName','nom','source','traffic_source','campaign_id','campaignId','campaign_name','form_name','formName','category','categorie','type_soin','service','soin','message','notes','contact','location','form']);
function extraInfo(b){const out={};const custom=b.customData||b.custom_fields||b.customFields||b.fields||b.formData||{};if(custom&&typeof custom==='object'&&!Array.isArray(custom))for(const [k,v] of Object.entries(custom)){if(v!==''&&v!==null&&v!==undefined)out[k]=typeof v==='object'?JSON.stringify(v):String(v)};for(const [k,v] of Object.entries(b||{})){if(!reserved.has(k)&&['string','number','boolean'].includes(typeof v)&&String(v).trim())out[k]=String(v)}return out}
async function ingest(req,forcedInstitutId=""){
 if(req.headers.get("x-webhook-secret")!==process.env.GHL_WEBHOOK_SECRET)return NextResponse.json({error:"Unauthorized"},{status:401});
 const b=await req.json(),s=await loadState();const locationId=String(pick(b,"location_id","locationId","location.id")||"");const formId=String(pick(b,"form_id","formId","form.id","form_submission_id")||"");let institutId=forcedInstitutId;let integration=null;
 if(!institutId){integration=(s.integrations||[]).find(x=>x.provider==="ghl"&&String(x.locationId||"")===locationId);institutId=integration?.institutId||""}if(!institutId)return NextResponse.json({error:"Aucun client Presty associé à ce Location ID GHL"},{status:404});if(!s.instituts.some(i=>i.id===institutId))return NextResponse.json({error:"Compte client introuvable"},{status:404});if(!integration)integration=(s.integrations||[]).find(x=>x.provider==="ghl"&&x.institutId===institutId)||null;
 const mapping=(integration?.forms||[]).find(x=>String(x.formId||"")===formId)||{};const contactId=String(pick(b,"contact_id","contactId","contact.id","id")||"");const email=String(pick(b,"email","contact.email")||"");const phone=String(pick(b,"phone","telephone","contact.phone")||"");const existing=s.leads.find(x=>x.institutId===institutId&&((contactId&&x.ghlContactId===contactId)||(email&&x.email===email)||(phone&&x.telephone===phone)));
 const formName=String(mapping.formName||mapping.name||pick(b,"form_name","formName","form.name")||existing?.formName||"");const campaignName=String(pick(b,"campaign_name","campaignName")||"");
 const patch=normalizeLead({...existing,id:existing?.id||uid(),institutId,dateContact:existing?.dateContact||today(),prenom:pick(b,"first_name","firstName","prenom","contact.firstName")||existing?.prenom||"",nom:pick(b,"last_name","lastName","nom","contact.lastName")||existing?.nom||"",telephone:phone||existing?.telephone||"",email:email||existing?.email||"",category:mapping.category||pick(b,"category","categorie")||existing?.category||"Autres",typeSoin:mapping.service||pick(b,"type_soin","service","soin")||existing?.typeSoin||"",formName:formName||campaignName||existing?.formName||"Formulaire GHL",source:formName||campaignName||existing?.source||"Formulaire GHL",channel:pick(b,"source","traffic_source")||existing?.channel||"GoHighLevel",problematique:pick(b,"problematique","message","notes")||existing?.problematique||"",additionalInfo:{...(existing?.additionalInfo||{}),...extraInfo(b)},statut:existing?.statut||"Nouveau lead",converted:existing?.converted||false,value:existing?.value||0,ghlContactId:contactId||existing?.ghlContactId||"",ghlLocationId:locationId||existing?.ghlLocationId||"",ghlFormId:formId||existing?.ghlFormId||"",ghlCampaignId:String(pick(b,"campaign_id","campaignId")||existing?.ghlCampaignId||""),updatedAt:nowIso(),activity:[...(existing?.activity||[]),{id:uid(),type:"Import GHL",text:existing?"Informations mises à jour depuis GoHighLevel":"Nouveau lead reçu depuis GoHighLevel",createdAt:nowIso()}]});
 s.leads=existing?s.leads.map(x=>x.id===existing.id?patch:x):[patch,...s.leads];await saveState(s);return NextResponse.json({ok:true,leadId:patch.id,created:!existing,institutId,formMapped:Boolean(mapping.formId)});
}
export async function POST(req,{params}={}){let forced="";if(params){const p=await params;forced=p?.institutId||""}try{return await ingest(req,forced)}catch(e){return NextResponse.json({error:e.message},{status:500})}}
export async function POST_GENERIC(req){try{return await ingest(req,"")}catch(e){return NextResponse.json({error:e.message},{status:500})}}
