'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { browserSupabase } from '@/lib/supabase';
import { CATEGORIES } from '@/lib/state';
import { periodRows } from '@/lib/stats';
import Brand from './Brand';
import { LayoutDashboard, Users, Kanban, Megaphone, Settings, LogOut, Plus, Search, ChevronRight, TrendingUp, Wallet, UserPlus, CalendarDays, CheckCircle2, Menu, X } from 'lucide-react';
const euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n||0); const pct=n=>`${(n||0).toFixed(1)} %`;
async function token(){return (await browserSupabase().auth.getSession()).data.session?.access_token}
export default function PortalApp(){const router=useRouter();const [ctx,setCtx]=useState(null);const [section,setSection]=useState('dashboard');const [mobile,setMobile]=useState(false);const [loading,setLoading]=useState(true);const [modal,setModal]=useState(false);const [selected,setSelected]=useState(null);const now=new Date();const [year,setYear]=useState(now.getFullYear());const [month,setMonth]=useState(now.getMonth()+1);const [category,setCategory]=useState('Toutes');
async function load(){setLoading(true);const r=await fetch('/api/state',{headers:{authorization:`Bearer ${await token()}`}});if(r.status===401){router.replace('/login');return;}setCtx(await r.json());setLoading(false)} useEffect(()=>{load()},[]);
async function save(state){const r=await fetch('/api/state',{method:'PUT',headers:{'content-type':'application/json',authorization:`Bearer ${await token()}`},body:JSON.stringify({state})});const j=await r.json();if(!r.ok)alert(j.error);else setCtx(v=>({...v,state:j.state}))}
async function logout(){await browserSupabase().auth.signOut();router.replace('/login')}
if(loading||!ctx)return <div className="centerScreen"><div className="spinner"/></div>;
const admin=ctx.role==='agency_admin';const institutes=ctx.state.instituts;const activeId=admin?(institutes[0]?.id||null):ctx.institutId;const institutId=selected||activeId;const stats=institutId?periodRows(ctx.state,institutId,year,month,category):{leads:0,rdv:0,present:0,clients:0,spend:0,ca:0,cpl:0,cac:0,conversion:0,attendance:0,roi:0};
const nav=[['dashboard','Vue d’ensemble',LayoutDashboard],['prospects','Prospects',Kanban],...(admin?[['instituts','Instituts',Users],['campagnes','Campagnes & dépenses',Megaphone]]:[]),['settings','Paramètres',Settings]];
return <div className="appShell"><aside className={`sidebar ${mobile?'open':''}`}><div className="sideTop"><Brand/><button className="mobileClose" onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={section===id?'active':''} onClick={()=>{setSection(id);setMobile(false)}}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="sideBottom"><div className="userChip"><div className="avatar">{(ctx.name||'P').slice(0,1).toUpperCase()}</div><div><strong>{ctx.name}</strong><span>{admin?'Administrateur Presty':'Compte institut'}</span></div></div><button onClick={logout}><LogOut size={18}/> Déconnexion</button></div></aside><main className="main"><header className="topbar"><button className="mobileMenu" onClick={()=>setMobile(true)}><Menu/></button><div><h1>{nav.find(x=>x[0]===section)?.[1]}</h1><p>{admin?'Pilotage global de vos clients':'Suivi de vos performances'}</p></div>{admin&&institutes.length>0&&<select value={institutId||''} onChange={e=>setSelected(e.target.value)}>{institutes.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select>}</header>{section==='dashboard'&&<Dashboard stats={stats} state={ctx.state} institutId={institutId} year={year} month={month} setYear={setYear} setMonth={setMonth} category={category} setCategory={setCategory}/>} {section==='instituts'&&admin&&<Instituts state={ctx.state} open={()=>setModal(true)} setSelected={setSelected} go={()=>setSection('dashboard')}/>} {section==='prospects'&&<Prospects state={ctx.state} institutId={institutId} save={save}/>} {section==='campagnes'&&admin&&<Campaigns state={ctx.state} institutId={institutId} save={save}/>} {section==='settings'&&<SettingsView/>}</main>{modal&&<CreateInstitut close={()=>setModal(false)} done={()=>{setModal(false);load()}}/>}</div>}
function Filters({year,month,setYear,setMonth,category,setCategory}){return <div className="filters"><select value={month} onChange={e=>setMonth(+e.target.value)}>{['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'].map((m,i)=><option value={i+1} key={m}>{m}</option>)}</select><select value={year} onChange={e=>setYear(+e.target.value)}>{[2025,2026,2027].map(y=><option key={y}>{y}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)}><option>Toutes</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></div>}
function Dashboard(p){const s=p.stats;return <div className="content"><div className="pageActions"><div><h2>Performance mensuelle</h2><p>Les chiffres se recalculent automatiquement depuis le CRM et les dépenses.</p></div><Filters {...p}/></div><div className="kpiGrid"><Kpi icon={Wallet} label="CA généré" value={euro(s.ca)} trend="Chiffre d’affaires converti"/><Kpi icon={TrendingUp} label="ROI" value={`x${s.roi.toFixed(1)}`} trend="CA ÷ dépenses"/><Kpi icon={UserPlus} label="Prospects" value={s.leads} trend={`${euro(s.cpl)} par prospect`}/><Kpi icon={CalendarDays} label="Rendez-vous" value={s.rdv} trend={`${pct(s.attendance)} de présence`}/><Kpi icon={CheckCircle2} label="Clientes signées" value={s.clients} trend={`${pct(s.conversion)} de conversion`}/><Kpi icon={Megaphone} label="Dépenses" value={euro(s.spend)} trend={`${euro(s.cac)} par cliente`}/></div><div className="grid2"><section className="panel"><div className="panelHead"><div><h3>Tunnel de conversion</h3><p>Du prospect à la cliente signée</p></div></div><div className="funnel">{[['Prospects',s.leads],['RDV',s.rdv],['Présentes',s.present],['Clientes',s.clients]].map(([l,v],i)=><div key={l}><span>{l}</span><strong>{v}</strong>{i<3&&<ChevronRight/>}</div>)}</div></section><section className="panel"><div className="panelHead"><div><h3>Rentabilité</h3><p>Vue synthétique du mois</p></div></div><div className="profit"><div><span>Chiffre d’affaires</span><strong>{euro(s.ca)}</strong></div><div><span>Investissement publicitaire</span><strong>{euro(s.spend)}</strong></div><div className="profitNet"><span>Retour brut</span><strong>{euro(s.ca-s.spend)}</strong></div></div></section></div></div>}
function Kpi({icon:Icon,label,value,trend}){return <section className="kpi"><div className="kpiIcon"><Icon size={20}/></div><span>{label}</span><strong>{value}</strong><small>{trend}</small></section>}
function Instituts({state,open,setSelected,go}){return <div className="content"><div className="pageActions"><div><h2>Vos instituts</h2><p>Créez et gérez les accès clients sans ouvrir Supabase.</p></div><button className="primary inline" onClick={open}><Plus size={18}/> Ajouter un institut</button></div><div className="cardsList">{state.instituts.map(i=><button className="clientCard" key={i.id} onClick={()=>{setSelected(i.id);go()}}><div className="clientLogo">{i.name.slice(0,2).toUpperCase()}</div><div><strong>{i.name}</strong><span>{i.ville||'Ville non renseignée'} · {i.email}</span></div><div className={`status ${i.active?'ok':'off'}`}>{i.active?'Actif':'Désactivé'}</div><ChevronRight/></button>)}</div></div>}
function Prospects({state,institutId,save}){const [q,setQ]=useState('');const leads=state.leads.filter(l=>l.institutId===institutId&&(`${l.firstName} ${l.lastName} ${l.phone}`.toLowerCase().includes(q.toLowerCase())));const cols=['Non qualifié','Appel 1','Appel 2','RDV fixé','Client converti'];function move(id,status){save({...state,leads:state.leads.map(l=>l.id===id?{...l,status,converted:status==='Client converti'?true:l.converted}:l)})}return <div className="content"><div className="pageActions"><div><h2>Pipeline prospects</h2><p>Suivez chaque opportunité jusqu’à la conversion.</p></div><div className="search"><Search size={17}/><input placeholder="Rechercher…" value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="kanban">{cols.map(c=><div className="column" key={c}><div className="columnHead"><strong>{c}</strong><span>{leads.filter(l=>l.status===c).length}</span></div>{leads.filter(l=>l.status===c).map(l=><article className="leadCard" key={l.id}><div><strong>{l.firstName||'Sans prénom'} {l.lastName||''}</strong><span>{l.phone||l.email||'Aucun contact'}</span></div><small>{l.problem||'Problématique non renseignée'}</small><select value={l.status} onChange={e=>move(l.id,e.target.value)}>{cols.map(x=><option key={x}>{x}</option>)}</select></article>)}</div>)}</div></div>}
function Campaigns({state,institutId,save}){const [name,setName]=useState('');const [cat,setCat]=useState('Minceur');const [amount,setAmount]=useState('');const now=new Date();function addCampaign(e){e.preventDefault();save({...state,campaigns:[...state.campaigns,{id:crypto.randomUUID(),institutId,name,category:cat,active:true}]});setName('')}function addExpense(campaignId){if(!amount)return;save({...state,expenses:[...state.expenses,{id:crypto.randomUUID(),institutId,campaignId,year:now.getFullYear(),month:now.getMonth()+1,amount:+amount}]});setAmount('')}const cs=state.campaigns.filter(c=>c.institutId===institutId);return <div className="content"><div className="grid2"><section className="panel"><div className="panelHead"><div><h3>Ajouter un soin / campagne</h3><p>Rattaché à une catégorie de performance</p></div></div><form className="stackForm" onSubmit={addCampaign}><label>Nom<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex. Cryolipolyse" required/></label><label>Catégorie<select value={cat} onChange={e=>setCat(e.target.value)}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><button className="primary">Ajouter</button></form></section><section className="panel"><div className="panelHead"><div><h3>Dépense du mois</h3><p>Saisie manuelle par Presty</p></div></div><label>Montant à affecter<input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="850"/></label><div className="campaignList">{cs.map(c=><button key={c.id} onClick={()=>addExpense(c.id)}><div><strong>{c.name}</strong><span>{c.category}</span></div><Plus size={17}/></button>)}</div></section></div></div>}
function SettingsView(){return <div className="content"><section className="panel"><h3>Paramètres</h3><p className="muted">Les paramètres avancés, la personnalisation du logo et le domaine seront ajoutés dans les prochaines versions sans écraser les données.</p></section></div>}
function CreateInstitut({close,done}){const [f,setF]=useState({name:'',ville:'',contactName:'',email:'',password:''});const [error,setError]=useState('');async function submit(e){e.preventDefault();const r=await fetch('/api/instituts',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${await token()}`},body:JSON.stringify(f)});const j=await r.json();if(!r.ok){setError(j.error);return;}done()}return <div className="modalBack"><div className="modal"><div className="modalHead"><div><span className="eyebrow">NOUVEL ACCÈS</span><h2>Ajouter un institut</h2></div><button onClick={close}><X/></button></div><form onSubmit={submit}><div className="formGrid"><label>Nom de l’institut<input value={f.name} onChange={e=>setF({...f,name:e.target.value})} required/></label><label>Ville<input value={f.ville} onChange={e=>setF({...f,ville:e.target.value})}/></label><label>Nom du contact<input value={f.contactName} onChange={e=>setF({...f,contactName:e.target.value})}/></label><label>Email de connexion<input type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})} required/></label><label className="full">Mot de passe temporaire<input minLength="8" value={f.password} onChange={e=>setF({...f,password:e.target.value})} required/></label></div>{error&&<div className="error">{error}</div>}<div className="modalActions"><button type="button" className="ghost" onClick={close}>Annuler</button><button className="primary inline">Créer le compte client</button></div></form></div></div>}
