const TOKEN_URL="https://services.leadconnectorhq.com/oauth/token";
const API_BASE="https://services.leadconnectorhq.com";
const REDIRECT_URI=process.env.GHL_REDIRECT_URI||"https://portail-client-brown.vercel.app/api/integrations/crm/callback";

function credentials(){const clientId=process.env.GHL_CLIENT_ID||"",clientSecret=process.env.GHL_CLIENT_SECRET||"";if(!clientId||!clientSecret)throw new Error("GHL_CLIENT_ID / GHL_CLIENT_SECRET manquants");return{clientId,clientSecret}}
export function appId(){return process.env.GHL_APP_ID||String(process.env.GHL_CLIENT_ID||"").split("-")[0]||"6a797b77d0061c571740aa09"}
async function tokenRequest(params){const response=await fetch(TOKEN_URL,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams(params),cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok){const msg=Array.isArray(body?.message)?body.message.join(", "):body?.message||body?.error_description||body?.error||`Erreur OAuth GHL (${response.status})`;throw new Error(msg)}return body}
export async function exchangeAuthorizationCode(code){const{clientId,clientSecret}=credentials();return tokenRequest({client_id:clientId,client_secret:clientSecret,grant_type:"authorization_code",code:String(code||""),user_type:"Company",redirect_uri:REDIRECT_URI})}
export async function refreshAccessToken(refreshToken,userType="Company"){const{clientId,clientSecret}=credentials();return tokenRequest({client_id:clientId,client_secret:clientSecret,grant_type:"refresh_token",refresh_token:String(refreshToken||""),user_type:String(userType||"Company"),redirect_uri:REDIRECT_URI})}
export function normalizeToken(body,previous={}){const expiresIn=Number(body?.expires_in||86400);return{locationId:String(body?.locationId||previous.locationId||""),companyId:String(body?.companyId||previous.companyId||""),userType:String(body?.userType||body?.user_type||previous.userType||"Location"),accessToken:String(body?.access_token||previous.accessToken||""),refreshToken:String(body?.refresh_token||previous.refreshToken||""),tokenType:String(body?.token_type||previous.tokenType||"Bearer"),scope:Array.isArray(body?.scope)?body.scope.join(" "):String(body?.scope||previous.scope||""),expiresAt:new Date(Date.now()+Math.max(60,expiresIn-120)*1000).toISOString(),updatedAt:new Date().toISOString(),installedAt:previous.installedAt||new Date().toISOString()}}
export function oauthInstallations(state){return Array.isArray(state?.ghlOAuth?.installations)?state.ghlOAuth.installations:[]}
export async function getValidAgencyToken(state,saveState){let item=state?.ghlOAuth?.agencyToken;if(!item?.accessToken)throw new Error("GoHighLevel n’est pas encore connecté au niveau agence");if(item.expiresAt&&new Date(item.expiresAt).getTime()>Date.now()+60000)return item; if(!item.refreshToken)throw new Error("Le token agence GHL a expiré. Reconnectez GoHighLevel.");item=normalizeToken(await refreshAccessToken(item.refreshToken,"Company"),item);state.ghlOAuth={...(state.ghlOAuth||{}),connected:true,agencyToken:item};await saveState(state);return item}
export async function getInstalledLocations(state,saveState){const agency=await getValidAgencyToken(state,saveState);const id=appId();const q=new URLSearchParams({companyId:agency.companyId,appId:id,skip:"0",limit:"200",isInstalled:"true"});const r=await fetch(`${API_BASE}/oauth/installedLocations?${q}`,{headers:{Accept:"application/json",Authorization:`Bearer ${agency.accessToken}`,Version:"2021-07-28"},cache:"no-store"});const b=await r.json().catch(()=>({}));if(!r.ok){const msg=b?.message||b?.error||`Impossible de récupérer les sous-comptes installés (${r.status})`;if(r.status===401||r.status===403)throw new Error(`${msg}. Vérifiez que les scopes oauth.readonly et oauth.write sont cochés dans l’app HighLevel.`);throw new Error(msg)}return Array.isArray(b?.locations)?b.locations:[]}
export async function exchangeLocationToken(state,locationId,saveState){const agency=await getValidAgencyToken(state,saveState);const body=new URLSearchParams({companyId:agency.companyId,locationId:String(locationId)});const r=await fetch(`${API_BASE}/oauth/locationToken`,{method:"POST",headers:{Accept:"application/json",Authorization:`Bearer ${agency.accessToken}`,Version:"2021-07-28","Content-Type":"application/x-www-form-urlencoded"},body,cache:"no-store"});const b=await r.json().catch(()=>({}));if(!r.ok){const msg=b?.message||b?.error||`Impossible de créer le token du sous-compte (${r.status})`;if(r.status===401||r.status===403)throw new Error(`${msg}. Le scope oauth.write est requis dans l’app HighLevel.`);throw new Error(msg)}return normalizeToken({...b,locationId,companyId:agency.companyId},{locationId,companyId:agency.companyId,userType:"Location"})}
export async function syncInstalledLocations(state,saveState){const locations=await getInstalledLocations(state,saveState);let installs=oauthInstallations(state);for(const loc of locations.filter(x=>x?.isInstalled!==false)){const locationId=String(loc._id||loc.id||loc.locationId||"");if(!locationId)continue;let item=installs.find(x=>String(x.locationId)===locationId);if(!item?.accessToken){item=await exchangeLocationToken(state,locationId,saveState)}item={...item,locationId,locationName:loc.name||item.locationName||locationId,address:loc.address||item.address||"",isInstalled:true};installs=installs.some(x=>String(x.locationId)===locationId)?installs.map(x=>String(x.locationId)===locationId?item:x):[...installs,item]}state.ghlOAuth={...(state.ghlOAuth||{}),connected:true,installations:installs,updatedAt:new Date().toISOString()};await saveState(state);return installs}
export async function getValidLocationToken(state,locationId,saveState){let installs=oauthInstallations(state);let item=installs.find(x=>String(x.locationId)===String(locationId));if(!item?.accessToken&&state?.ghlOAuth?.agencyToken){item=await exchangeLocationToken(state,locationId,saveState);installs=installs.some(x=>String(x.locationId)===String(locationId))?installs.map(x=>String(x.locationId)===String(locationId)?item:x):[...installs,item];state.ghlOAuth={...(state.ghlOAuth||{}),installations:installs};await saveState(state)}if(!item?.accessToken)throw new Error("Ce sous-compte GHL n’est pas autorisé dans Presty CRM");if(item.expiresAt&&new Date(item.expiresAt).getTime()>Date.now()+60000)return item.accessToken;if(!item.refreshToken)throw new Error("Le jeton GHL a expiré. Synchronisez de nouveau les sous-comptes depuis l’administration.");const refreshed=normalizeToken(await refreshAccessToken(item.refreshToken,"Location"),item);state.ghlOAuth={...(state.ghlOAuth||{}),installations:installs.map(x=>String(x.locationId)===String(locationId)?refreshed:x)};await saveState(state);return refreshed.accessToken}
export {REDIRECT_URI};
