import { migrate, emptyState } from './state';
const url=()=>process.env.NEXT_PUBLIC_SUPABASE_URL;
const key=()=>process.env.SUPABASE_SERVICE_ROLE_KEY;
async function request(path,options={}){if(!url()||!key())throw new Error('Variables Supabase serveur manquantes');const res=await fetch(`${url()}${path}`,{...options,headers:{apikey:key(),Authorization:`Bearer ${key()}`,'Content-Type':'application/json',...(options.headers||{})},cache:'no-store'});const text=await res.text();const data=text?JSON.parse(text):null;if(!res.ok)throw new Error(data?.message||data?.msg||data?.error_description||`Supabase ${res.status}`);return data;}
export async function authProfile(req){const token=(req.headers.get('authorization')||'').replace(/^Bearer\s+/,'');if(!token)return null;const ur=await fetch(`${url()}/auth/v1/user`,{headers:{apikey:process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,Authorization:`Bearer ${token}`},cache:'no-store'});if(!ur.ok)return null;const user=await ur.json();const rows=await request(`/rest/v1/profiles?id=eq.${user.id}&select=*`);return rows?.[0]?{...rows[0],user}:null;}
export async function createAuthUser({email,password,name}){return request('/auth/v1/admin/users',{method:'POST',body:JSON.stringify({email,password,email_confirm:true,user_metadata:{name}})});}
export async function deleteAuthUser(id){return request(`/auth/v1/admin/users/${id}`,{method:'DELETE'});}
export async function insertProfile(profile){return request('/rest/v1/profiles',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(profile)});}
export async function countAdmins(){const rows=await request('/rest/v1/profiles?role=eq.agency_admin&select=id');return rows.length;}
export async function loadState(){const rows=await request('/rest/v1/app_state?id=eq.main&select=payload');const state=migrate(rows?.[0]?.payload||emptyState());if(JSON.stringify(state)!==JSON.stringify(rows?.[0]?.payload||{}))await saveState(state);return state;}
export async function saveState(state){const payload=migrate(state);await request('/rest/v1/app_state?id=eq.main',{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({payload,updated_at:new Date().toISOString()})});return payload;}
